### ISSUE TITLE
Ability to identify unique contacts

### ISSUE THREAD

**Issue by umesh-qs** [erasmus-without-paper/ewp-specs-api-institutions#12]
Is there any reason why contacts are not given a unique id similar to iia_id in IIA api? If we can have a unique id then it can be used in IIA api as well.

**Comment by MartaJuzepczuk** [comment]
You would like to have Contacts API?

**Comment by umesh-qs** [comment]
Not really. In institutions API we have below section. A unique id can be given here
        <c:contact>
            
            <c:contact-name>IRO Office</c:contact-name>
            <c:email>iro@uio.no</c:email>
        </c:contact>

**Comment by MartaJuzepczuk** [comment]
If  you receive such an id in IIAs response and you do not have the Contacts API, than you have to call institutions API and search ids on your own. Does not seem convenient.

**Comment by umesh-qs** [comment]
I am not sure if I have understood your comment.  If we can have something like below. Since IIA contact is an institution/ounit contact, Id:ASADENKVFFFJHJJ can be sent in IIA API. Other contact info need not be passed and mapping becomes easier

<c:contact>
<c:contact-id>ASADENKVFFFJHJJ</c:contact-id>
<c:contact-name>IRO Office</c:contact-name>
<c:email>iro@uio.no</c:email>
</c:contact>

**Comment by MartaJuzepczuk** [comment]
> Since IIA contact is an institution/ounit contact

Maybe, but I'm not sure.

>  Other contact info need not be passed and mapping becomes easier

You are right. But if I get an IIAs response and see `<c:contact-id>ASADENKVFFFJHJJ</c:contact-id>` than what should I do?

**Comment by umesh-qs** [comment]
If contact-id is there then you can sync the partner contacts without any confusion. In IIA if partner contact-id is there then you can easily map signing contact and the agreement contact coming from partner, since they would already have been mapped at the time of institution/ounit import

**Comment by MartaJuzepczuk** [comment]
Let's wait for the opinion of the other network users @erasmus-without-paper/all-members

**Comment by wrygiel** [comment]
There has been a draft proposal of introducing unique person identifiers.
It has been abandoned, because there seemed to be no need for such (at the
time it has been proposed), and making these identifiers really unique was
tricky (especially for some edge cases, like multiple nationalities).

You can still find this proposal in a sperate GitHub repository (it's no
longer linked at the developers page, I believe).

(Sorry for not pasting a link, but I'm writing this on a plane. Will do
that later on if you don't find it.)

**Comment by umesh-qs** [comment]
I am not sure what person mean here. I am referring to only contacts of Institution. Every institution should have a unique id in their system database in the same way as they have a unique id for an IIA.

**Comment by wrygiel** [comment]
Sorry, I misunderstood. Ignore my comment then.

**Comment by EvelienRenders** [comment]
Perhaps replying to this now is not relevant anymore, but I'm very curious if this discussion was continued somewhere, or if it has been abandoned. If the latter, the issue can be closed. If the former, I'm curious what became of it, because if I understand correctly there is no way to manage 'contacts' separate from the IIA's right now? It would be lovely if the contacts that HEI's register in the ErasmusDashboard/other system, would be shared via EWP, so we can keep our CRM up-to-date via that API.

@umesh-qs @wrygiel @MartaJuzepczuk

**Comment by janinamincer-daszkiewicz** [comment]
No, the discussion has not been continued. It seems that nobody (but Umesh) at that time has been interested in strong and unique identification of contacts.
