### ISSUE TITLE
Credit/Grading Scheme in Inst/Org Unit?

### ISSUE THREAD

**Issue by kaiqu** [erasmus-without-paper/ewp-specs-api-institutions#9]
In the current model, Inst/Org Unit has an optional Credit Scheme and Grading Scheme, which are not represented in the Institutions/OUnits APIs. Presumably, it was thought that a HEI (or even an OUnit) could use the same Credit and/or Grading Scheme all over, and therefore not have to specify it at the LOI level...

I thought we had discussed this before, but I can't find it - do you remember anything about this, @wrygiel ?

**Comment by wrygiel** [comment]
I don't remember discussing this topic. However, having this in a view (API) on deeper level, does not prevent having it on an shallower level in the model (database).

In other words, if institution has it, say, on ounit level, it still can dynamically map it to the LOI level (so that clients won't be required to do this themselves). Do you think it's really useful to allow exposure on all the levels? Perhaps exposing just the bottom "end result" is enough?

**Comment by kaiqu** [comment]
Sounds good to me.
